# Generated by Django 4.1.1 on 2022-09-26 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование услуги')),
                ('price', models.IntegerField(verbose_name='Цена покупки услуги')),
            ],
            options={
                'verbose_name': 'Услуга сайта',
                'verbose_name_plural': 'Услуги сайта',
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='TestsNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=1000, verbose_name='Наименование теста')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'TestsNames',
            },
        ),
        migrations.CreateModel(
            name='UsersPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баллы пользователя',
                'verbose_name_plural': 'Баллы пользователей',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='TestsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('answers', models.CharField(max_length=1000, verbose_name='Ответы')),
                ('right_answer', models.CharField(max_length=500, verbose_name='Правильный ответ')),
                ('bonus', models.IntegerField(verbose_name='Цена начисления за правильный ответ')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.testsnames')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'TestQuestions',
            },
        ),
    ]
