# Generated by Django 4.1.1 on 2022-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspoints',
            name='color',
            field=models.CharField(default=0, max_length=50, verbose_name='Цвет фона'),
            preserve_default=False,
        ),
    ]
