# Generated by Django 4.1.1 on 2022-09-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_goods_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='Ответ')),
                ('bonus', models.IntegerField(verbose_name='Цена начисления за правильный ответ')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.testsquestions')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'TestAnswers',
            },
        ),
    ]
