# Generated by Django 4.1.1 on 2022-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_testsanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsquestions',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='testsquestions',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='testsquestions',
            name='right_answer',
        ),
        migrations.AddField(
            model_name='testsanswers',
            name='right_answer',
            field=models.CharField(default=0, max_length=500, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
    ]
