# Generated by Django 4.1.1 on 2022-09-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_remove_testsanswers_right_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspoints',
            name='done_tests',
            field=models.CharField(default=0, max_length=1000, verbose_name='Пройденные тесты'),
            preserve_default=False,
        ),
    ]
